# Generated by Django 5.1 on 2024-09-01 23:41

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', encrypted_model_fields.fields.EncryptedCharField()),
                ('tenant_id', encrypted_model_fields.fields.EncryptedCharField()),
                ('client_secret', encrypted_model_fields.fields.EncryptedCharField()),
            ],
        ),
        migrations.AlterField(
            model_name='offboarding',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete')], default='Pending', max_length=50),
        ),
    ]
