# Generated by Django 5.1 on 2024-09-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingfield',
            name='options',
            field=models.TextField(blank=True, help_text='Comma-separated options for dropdown fields.'),
        ),
        migrations.AlterField(
            model_name='onboardingfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Single Line of Text'), ('textarea', 'Multiple Lines of Text'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'Date/Time'), ('dropdown', 'Dropdown')], max_length=50),
        ),
    ]
