# Generated by Django 5.1 on 2024-09-04 03:33

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_azurecredentials_alter_offboarding_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurecredentials',
            name='smtp_host',
            field=models.CharField(default='smtp.example.com', max_length=100),
        ),
        migrations.AddField(
            model_name='azurecredentials',
            name='smtp_password',
            field=encrypted_model_fields.fields.EncryptedCharField(default='password'),
        ),
        migrations.AddField(
            model_name='azurecredentials',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='azurecredentials',
            name='smtp_user',
            field=models.CharField(default='user@example.com', max_length=100),
        ),
    ]
