# Generated by Django 5.1 on 2024-09-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_onboarding_field_remove_onboarding_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurecredentials',
            name='key_identifier',
            field=models.CharField(default='https://example.vault.azure.net/keys/placeholderkey/00000000000000000000000000000000', max_length=200),
        ),
        migrations.AlterField(
            model_name='azurecredentials',
            name='client_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='azurecredentials',
            name='client_secret',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='azurecredentials',
            name='smtp_password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AlterField(
            model_name='azurecredentials',
            name='tenant_id',
            field=models.CharField(max_length=100),
        ),
    ]
