# Generated by Django 5.1 on 2024-09-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_azurecredentials_key_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurecredentials',
            name='container_name',
            field=models.CharField(default='default_container', help_text='Azure Blob Storage Container Name', max_length=100),
        ),
        migrations.AddField(
            model_name='azurecredentials',
            name='storage_account_name',
            field=models.CharField(default='default_storage_account', help_text='Azure Storage Account Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='azurecredentials',
            name='key_identifier',
            field=models.CharField(help_text='URL of the key in Azure Key Vault', max_length=200),
        ),
    ]
