# Generated by Django 5.1 on 2024-09-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_azurecredentials_container_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurecredentials',
            name='key_name',
            field=models.CharField(default='key name', max_length=100),
        ),
        migrations.AddField(
            model_name='azurecredentials',
            name='vault_name',
            field=models.CharField(default='vault name', max_length=100),
        ),
    ]
