# Generated by Django 5.1 on 2024-09-08 19:19

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_azurecredentials_key_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azurecredentials',
            name='key_identifier',
        ),
        migrations.RemoveField(
            model_name='azurecredentials',
            name='key_name',
        ),
        migrations.RemoveField(
            model_name='azurecredentials',
            name='vault_name',
        ),
        migrations.AlterField(
            model_name='azurecredentials',
            name='client_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='azurecredentials',
            name='container_name',
            field=models.CharField(default='default_container', max_length=100),
        ),
        migrations.AlterField(
            model_name='azurecredentials',
            name='smtp_password',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='azurecredentials',
            name='storage_account_name',
            field=models.CharField(default='default_storage_account', max_length=100),
        ),
    ]
